[tool.poetry]
name = "md2api"
version = "1.0.0"
description = ""
authors = ["sumeshi <j15322sn@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
markdown = "^3.3.4"
GitPython = "^3.1.20"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
